#评论区
comments:
  service: artalk
  utterances:
    repo: fengdaizang/blog-comments
  beaudar:
    repo: fengdaizang/blog-comments
  # Artalk
  # https://artalk.js.org/
  artalk:
    css: https://unpkg.com/artalk@2.7/dist/Artalk.css
    js: https://unpkg.com/artalk@2.7/dist/Artalk.js
    server: https://thcwl.com/artalk/
    placeholder: ''
    darkMode: auto