


#评论区
comments:
  service: artalk
  utterances:
    repo: fengdaizang/blog-comments
  beaudar:
    repo: fengdaizang/blog-comments
  giscus:
    src: https://giscus.app/client.js
    data-repo: fengdaizang/blog-comments # [在此输入仓库]
    data-repo-id: # [在此输入仓库 ID]
    data-category: # [在此输入分类名]
    data-category-id:
    data-mapping: pathname
    data-strict: 0
    data-reactions-enabled: 1
    data-emit-metadata: 0
    data-input-position: top # top, bottom
    data-theme: preferred_color_scheme
    data-lang: zh-CN
    data-loading: lazy
    crossorigin: anonymous
  # Artalk
  # https://artalk.js.org/
  artalk:
    css: https://unpkg.com/artalk@2.7/dist/Artalk.css
    js: https://unpkg.com/artalk@2.7/dist/Artalk.js
    server: https://thcwl.com/artalk/
    placeholder: ''
    darkMode: auto